# Generated by Django 4.2 on 2024-10-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farm", "0002_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="produce",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="produce_images/"),
        ),
    ]
