# Generated by Django 4.2 on 2024-10-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farm", "0004_farmer_fingerprint_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farmer",
            name="fingerprint_token",
        ),
        migrations.AddField(
            model_name="farmer",
            name="face_encoding",
            field=models.TextField(blank=True, null=True),
        ),
    ]
